version: "3.8"
services:
  web:
    image: photogether-web:latest
    ports:
      - "8001:80"
    volumes:
      - ./config/master.key:/rails/config/master.key
      - ./tmp/storage:/rails/storage
      - ./log:/rails/log